<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/01/19 19:35:50
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
