<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/01/19 22:39:10
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
