<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/01/19 19:35:54
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'secure' => 
  array (
    'is_secure' => true,
  ),
  'signin' => 
  array (
    'is_secure' => true,
  ),
  'signout' => 
  array (
    'is_secure' => true,
  ),
);
