<?php
// auto-generated by sfRoutingConfigHandler
// date: 2018/01/19 21:19:00
return array(
'category' => new sfPropelRoute('/category/:slug.:sf_format', array (
  'module' => 'category',
  'action' => 'show',
  'sf_format' => 'html',
), array (
  'sf_format' => '(?:html|atom)',
), array (
  'model' => 'JobeetCategory',
  'type' => 'object',
)),
'job' => new sfPropelRouteCollection(array (
  'model' => 'JobeetJob',
  'column' => 'token',
  'object_actions' => 
  array (
    'publish' => 'put',
    'extend' => 'PUT',
  ),
  'name' => 'job',
  'requirements' => 
  array (
    'token' => '\\w+',
  ),
)),
'job_show_user' => new sfPropelRoute('/job/:company_slug/:location_slug/:id/:position_slug', array (
  'module' => 'job',
  'action' => 'show',
), array (
  'id' => '\\d+',
  'sf_method' => 
  array (
    0 => 'GET',
  ),
), array (
  'model' => 'JobeetJob',
  'type' => 'object',
  'method_for_criteria' => 'doSelectActive',
)),
'homepage' => new sfRoute('/', array (
  'module' => 'job',
  'action' => 'index',
), array (
), array (
)),
'api_jobs' => new sfPropelRoute('/api/:token/jobs.:sf_format', array (
  'module' => 'api',
  'action' => 'list',
), array (
  'sf_format' => '(?:xml|json|yaml)',
), array (
  'model' => 'JobeetJob',
  'type' => 'list',
  'method' => 'getForToken',
)),
);
